apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stackeye-prd

resources:
  - image-catalog.yaml
  # ObjectStore must be created before cluster references it
  - object-store.yaml
  - cluster.yaml
  - service-lb.yaml
  - service-tailscale.yaml
  - scheduled-backup.yaml
