# Staging environment values for stackeye-web

replicaCount: 2

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4

auth0:
  enabled: true
  domain: "stackeye-staging.auth0.com"
  clientId: ""
  baseUrl: "https://app.staging.stackeye.io"

ingress:
  hosts:
    - host: app.staging.stackeye.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: stackeye-web-staging-tls
      hosts:
        - app.staging.stackeye.io

sealedSecrets:
  enabled: true
  encryptedData: {}
